<form name="forgotPasswordForm" id="forgot-password-form"  method="POST"  action="index.php?go=reset_password_submit" >
<div class="new-account-wrap">
    <div id="message-zone" class="message-wrap" style="display:none;"></div>
     <div class="field-wrap">
        <label>Email</label>
        <input type="text" id="user-email" name="email" tabindex="0" value="" >
    </div>
   <div class="submit-wrap">
        <input type="submit" value="Submit" name="user-reset-password" onclick="return userAccount.forgotPasswordSubmit()">
    </div>

    <div class="field-wrap">
        <a href="index.php?go=login"><span class="login-link">I already have an account</span></a> <br/>
        <a href="index.php?go=new_account"><span class="user-new-account">Create new Account</span></a>
    </div>
</div>
</form>
